version: '3'

services:
  web:
    build: ./web
    platform: linux/x86_64
    container_name: php-apache
    ports:
      - 8080:80
    volumes:
      - ../backend:/var/www/html/backend
    privileged: true
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
    

  db:
    build: ./db
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    restart: always